# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_processor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(183, 200, 199);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 0, 381, 81))
        self.label.setObjectName("label")
        self.upload_button = QtWidgets.QPushButton(self.centralwidget)
        self.upload_button.setGeometry(QtCore.QRect(290, 440, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.upload_button.setFont(font)
        self.upload_button.setObjectName("upload_button")
        self.result_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.result_line_edit.setGeometry(QtCore.QRect(260, 360, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_line_edit.setFont(font)
        self.result_line_edit.setObjectName("result_line_edit")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(200, 110, 381, 191))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Heartbeat Classifier</span></p></body></html>"))
        self.upload_button.setText(_translate("MainWindow", "Upload"))
